name: Check Configurations Testnet

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  RPC_URL_ODYSSEY_TESTNET: ${{ secrets.RPC_URL_ODYSSEY_TESTNET }}

jobs:
  check-config:
    uses: ./.github/workflows/reusable-check-config.yaml
    with:
      network: testnet
    secrets: inherit
